// Paid-report PDF artifact — pure pdf-lib composition, no browser needed.
// Footer stays honest: sample data until live providers land.
import { PDFDocument, StandardFonts } from "pdf-lib";
import type { AuditReport } from "./types";

export async function buildPdf(report: AuditReport, paidOn: string): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  let page = doc.addPage([595, 842]);
  let y = 800;
  const size = 11;

  const line = (text: string, gap = 16, b = false) => {
    if (y < 60) {
      page = doc.addPage([595, 842]);
      y = 800;
    }
    page.drawText(text.slice(0, 110), { x: 50, y, size, font: b ? bold : font });
    y -= gap;
  };

  line(`cited — AEO Visibility Audit`, 22, true);
  line(`${report.domain} — paid audit, payment verified ${paidOn}`, 20);
  line(`Web visibility: ${report.webScore}/100 — cited in ${report.citationPct}% of prompts`, 20, true);
  line(`Buyer prompts tested:`, 16, true);
  for (const [i, p] of report.prompts.entries()) {
    line(`${i + 1}. ${p.cited ? "[cited]" : "[missed]"} ${p.text}`, 14);
  }
  line(`Who beats you:`, 16, true);
  for (const w of report.winners) {
    line(`${w.name} — ${w.page} (${w.cites}/10)`, 14);
  }
  line(`Checklist: FAQ ${report.extract.hasFAQ ? "yes" : "no"} / pricing ${report.extract.hasPricingTable ? "yes" : "no"} / schema ${report.extract.hasSchema ? "yes" : "no"} / llms.txt ${report.extract.hasLlmsTxt ? "yes" : "no"} / words ${report.extract.wordCount} vs ${report.extract.winnerAvgWords}`, 16, true);
  line(`5 fixes, impact order:`, 16, true);
  for (const [i, f] of report.fixes.entries()) {
    line(`${i + 1}. [${f.impact}/${f.effort}] ${f.title}`, 14);
    line(`   ${f.detail}`, 14);
  }
  line(`Sample report data - live provider check pending. Generated by cited.`, 16);
  return doc.save();
}
